---
title: "Raport"
author: "Agnieszka Chilimoniuk, nr indeksu 82140"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
# Projekt zaliczeniowy  


 
```{r, echo=F, results='hide'}
library(ggplot2)
library(tseries)
library(lmtest)
``` 

### Tabela

```{r,echo=F,results="asis"}
 library(knitr)

   if(file.exists("tbl")) {
  tabela <- get(load("tbl"))
  tabela <- as.data.frame(tabela)
  tabela <- kable(tabela)
  print(tabela)
}


```

### Mapa GUS

```{r, echo=F, results='asis'}

if(file.exists("Geo")) {
  mapag <- get(load("Geo"))
  print(mapag)
}

``` 

### Mapa GUS porownanie

```{r, echo=F, results='asis'}

if(file.exists("porown1")) {
  mapagp <- get(load("porown1"))
  print(mapagp)
}


``` 

### Mapa EUROSTAT

```{r, echo=F, results='asis'}

if(file.exists("eu")) {
  mapaeu <- get(load("eu"))
  print(mapaeu)
}

``` 

### Mapa EUROSTAT porownanie

```{r, echo=F, results='asis'}

if(file.exists("porown2")) {
  mapaeup <- get(load("porown2"))
  print(mapaeup)
}

``` 

### Szereg czasowy GUS

```{r, echo=F, results='asis'}

if(file.exists("wykresg")) {
  wykresg <- get(load("wykresg"))
  print(wykresg)
}

``` 

### Szereg czasowy GUS porownanie
```{r, echo=F, results='asis'}

if(file.exists("wykresg2")) {
  wykresg2 <- get(load("wykresg2"))
  print(wykresg2)
}

``` 

### Szereg czasowy EUROSTAT
```{r, echo=F, results='asis'}

if(file.exists("wykrese")) {
  wykrese <- get(load("wykrese"))
  print(wykrese)
}

``` 

### Szereg czasowy EUROSTAT porownanie
```{r, echo=F, results='asis'}

if(file.exists("wykrese2")) {
  wykrese2 <- get(load("wykrese2"))
  print(wykrese2)
}

``` 


